export const ATTENTION_ANALYSIS_OPENED = 'ATTENTION_ANALYSIS_OPENED';

export const INIT_FACE_DETECT = 'INIT_FACE_DETECT';

export const START_FACE_DETECT = 'START_FACE_DETECT';

export const STOP_FACE_DETECT = 'STOP_FACE_DETECT';

export const UPDATE_ATTENTION_STATUSES = 'UPDATE_ATTENTION_STATUSES';

export const SET_ATTENTION_ANALYSIS_READY = 'SET_ATTENTION_ANALYSIS_READY';
